// Generuje `src/lib/fixture.ts` z PRAWDZIWYCH plików, które dostaje sędzia:
//   przyklady/receipt.json  +  przyklady/odpowiedz.txt
//
// Zero wymyślonych kluczy i podpisów. Dzięki temu strona demo weryfikuje ten
// sam receipt, który przechodzi `simon --verify-receipt`.
//
// Uruchom: npm run fixtures
import { readFileSync, writeFileSync } from 'node:fs';

const receiptPath = new URL('../../przyklady/receipt.json', import.meta.url);
const outputPath = new URL('../../przyklady/odpowiedz.txt', import.meta.url);

const receiptJson = readFileSync(receiptPath, 'utf8').trim();
const output = readFileSync(outputPath, 'utf8');

// Sanity: plik musi być receiptem SIMON, nie pustym/śmieciowym.
const parsed = JSON.parse(receiptJson);
for (const pole of ['job_id', 'node_id', 'model_hash', 'output_digest', 'signer', 'signature']) {
  if (typeof parsed[pole] !== 'string' || !parsed[pole]) {
    throw new Error(`przyklady/receipt.json: brak pola "${pole}"`);
  }
}

const src = `// GENERATED by scripts/generate-fixtures.ts — do not edit by hand.
// Source of truth: przyklady/receipt.json + przyklady/odpowiedz.txt (the same
// files a judge gets). Regenerate with: npm run fixtures
import type { Receipt } from './receipt';

// Bajtowo dokładny receipt i odpowiedź — nie reformatujemy, bo odcisk liczy
// się z dokładnych bajtów JSON-a i tekstu.
export const RECEIPT_JSON = ${JSON.stringify(receiptJson)};
export const OUTPUT = ${JSON.stringify(output)};

export const RECEIPT: Receipt = JSON.parse(RECEIPT_JSON) as Receipt;
`;

writeFileSync(new URL('../src/lib/fixture.ts', import.meta.url), src);
console.log('wrote src/lib/fixture.ts from przyklady/');
