// Generuje `src/lib/fixture.ts` z PRAWDZIWYCH plików, które dostaje sędzia:
//   przyklady/receipt.json  +  przyklady/odpowiedz.txt            (poziom 0)
//   przyklady/receipt_m1.json + zadanie_m1.json + odpowiedz_m1.txt (poziom 1, M1)
//   przyklady/audyt_m3.json                                        (audyt M3)
//
// Zero wymyślonych kluczy i podpisów. Strona demo weryfikuje te same pliki,
// które przechodzą `simon verify`.
//
// Uruchom: npm run fixtures
import { readFileSync, writeFileSync } from 'node:fs';

const read = (p: string) => readFileSync(new URL(p, import.meta.url), 'utf8');
const readJson = (p: string) => read(p).trim();

const receiptJson = readJson('../../przyklady/receipt.json');
const output = read('../../przyklady/odpowiedz.txt');

const receiptM1Json = readJson('../../przyklady/receipt_m1.json');
const zadanieM1Json = readJson('../../przyklady/zadanie_m1.json');
const outputM1 = read('../../przyklady/odpowiedz_m1.txt');
const audytM3Json = readJson('../../przyklady/audyt_m3.json');

// Sanity: receipty muszą mieć wymagane pola.
for (const [nazwa, j] of [
  ['przyklady/receipt.json', receiptJson],
  ['przyklady/receipt_m1.json', receiptM1Json]
] as const) {
  const parsed = JSON.parse(j);
  for (const pole of ['job_id', 'node_id', 'model_hash', 'output_digest', 'signer', 'signature']) {
    if (typeof parsed[pole] !== 'string' || !parsed[pole]) {
      throw new Error(`${nazwa}: brak pola "${pole}"`);
    }
  }
}

const src = `// GENERATED by scripts/generate-fixtures.ts — do not edit by hand.
// Source of truth: przyklady/ (the same files a judge gets).
// Regenerate with: npm run fixtures
import type { Receipt, ZadanieM1 } from './receipt';

// Bajtowo dokładne dane — nie reformatujemy, bo odcisk liczy się z dokładnych
// bajtów JSON-a i tekstu.
export const RECEIPT_JSON = ${JSON.stringify(receiptJson)};
export const OUTPUT = ${JSON.stringify(output)};
export const RECEIPT: Receipt = JSON.parse(RECEIPT_JSON) as Receipt;

export const RECEIPT_M1_JSON = ${JSON.stringify(receiptM1Json)};
export const ZADANIE_M1: ZadanieM1 = JSON.parse(${JSON.stringify(zadanieM1Json)}) as ZadanieM1;
export const OUTPUT_M1 = ${JSON.stringify(outputM1)};
export const RECEIPT_M1: Receipt = JSON.parse(RECEIPT_M1_JSON) as Receipt;

export const AUDYT_M3_JSON = ${JSON.stringify(audytM3Json)};
`;

writeFileSync(new URL('../src/lib/fixture.ts', import.meta.url), src);
console.log('wrote src/lib/fixture.ts from przyklady/ (legacy + M1 + M3)');
