// Generates a real Ed25519 keypair and real signatures, then writes src/lib/fixture.ts.
// Run: npm run fixtures
import * as ed from '@noble/ed25519';
import { sha256 } from '@noble/hashes/sha256';
import { sha512 } from '@noble/hashes/sha512';
import { bytesToHex, randomBytes } from '@noble/hashes/utils';
import { writeFileSync } from 'node:fs';

ed.etc.sha512Sync = (...m) => sha512(ed.etc.concatBytes(...m));

const enc = new TextEncoder();
const PROMPT = 'Explain in one sentence why verifiable inference matters.';
const OUTPUT = 'Verifiable inference lets you audit what a remote node computed without trusting it.';

const priv = ed.utils.randomPrivateKey();
const pub = ed.getPublicKey(priv);
const outHash = sha256(enc.encode(OUTPUT));
const sig = ed.sign(outHash, priv);
if (!ed.verify(sig, outHash, pub)) throw new Error('self-check failed');

const valid = {
  job_id: '0x' + bytesToHex(randomBytes(16)),
  node_pubkey: 'ed25519:' + bytesToHex(pub),
  model: 'llama-3.1-8b',
  prompt_sha256: bytesToHex(sha256(enc.encode(PROMPT))),
  output: OUTPUT,
  output_sha256: bytesToHex(outHash),
  signature: 'ed25519_sig:' + bytesToHex(sig)
};
const tampered = { ...valid, output: OUTPUT + ' ' }; // hash and signature deliberately NOT updated

const src = `// GENERATED by scripts/generate-fixtures.ts. Real Ed25519 key and signature. Do not edit by hand.
import type { Receipt } from './receipt';

export const PROMPT = ${JSON.stringify(PROMPT)};

export const VALID_RECEIPT: Receipt = ${JSON.stringify(valid, null, 2)};

export const TAMPERED_RECEIPT: Receipt = ${JSON.stringify(tampered, null, 2)};
`;
writeFileSync(new URL('../src/lib/fixture.ts', import.meta.url), src);
console.log('wrote src/lib/fixture.ts');
