// GENERATED by scripts/generate-fixtures.ts — do not edit by hand.
// Source of truth: przyklady/receipt.json + przyklady/odpowiedz.txt (the same
// files a judge gets). Regenerate with: npm run fixtures
import type { Receipt } from './receipt';

// Bajtowo dokładny receipt i odpowiedź — nie reformatujemy, bo odcisk liczy
// się z dokładnych bajtów JSON-a i tekstu.
export const RECEIPT_JSON = "{\n  \"activation_hash\": \"toploc:NIE_POLICZONY\",\n  \"completion_tokens\": 60,\n  \"finished_at_us\": 1789760547717093,\n  \"job_id\": \"job-e267671122556bec\",\n  \"model_hash\": \"qwen3.8-27b\",\n  \"node_id\": \"de1cbe4d9a2abed30e2f27d2b9159aceedaef1a04ca260704e1ccda891416032\",\n  \"output_digest\": \"5f4af804357c8df0dc2c45c92d03d6af2a896cf2319c58dc65c388cd5c20ed7d\",\n  \"precision\": \"fp16\",\n  \"prompt_tokens\": 66,\n  \"runtime\": \"vllm/0.27.1\",\n  \"signature\": \"93de9d76c0ae9a70844b9f245e6964d0961d6ba27efa9a1a16c7cd3e7b98e50e9628195b3edbae2351e3e20c9ed3fa804df954732bfb4bd56394571fd338910f\",\n  \"signer\": \"de1cbe4d9a2abed30e2f27d2b9159aceedaef1a04ca260704e1ccda891416032\",\n  \"started_at_us\": 1789760547717093\n}";
export const OUTPUT = "We need answer user: \"Explain in two sentences why a signature does not prove a computation.\" Need likely about digital signatures? A signature proves authenticity/integrity of a message, not that a computation was performed or result correct. Need two sentences. Could be in context of zk? \"A signature";

export const RECEIPT: Receipt = JSON.parse(RECEIPT_JSON) as Receipt;
