// GENERATED by scripts/generate-fixtures.ts. Real Ed25519 key and signature. Do not edit by hand.
import type { Receipt } from './receipt';

export const PROMPT = "Explain in one sentence why verifiable inference matters.";

export const VALID_RECEIPT: Receipt = {
  "job_id": "0x818e96a1aa15e51bf0455f666f299f13",
  "node_pubkey": "ed25519:ef28909b9ab3c0476ee1af8a7124182f5ffff6078995bc8d2b334a62afe14de5",
  "model": "llama-3.1-8b",
  "prompt_sha256": "188b7c68248e3ea7e66b4ae359c4c0f1af898a4c388efb9d517d390537913a8d",
  "output": "Verifiable inference lets you audit what a remote node computed without trusting it.",
  "output_sha256": "a88133a6f88e6558e00a8c82bbf4f6632e66ad43f332f7e4e8d7a02ee6815a32",
  "signature": "ed25519_sig:0cda89675d97deb2f04c4ceceda57d3d1332e9a8039a4f2941a83005ae89626058afe16a61be8e2b5a2956156088824b3c0a8b8ebf26d935ff9347fef9342a02"
};

export const TAMPERED_RECEIPT: Receipt = {
  "job_id": "0x818e96a1aa15e51bf0455f666f299f13",
  "node_pubkey": "ed25519:ef28909b9ab3c0476ee1af8a7124182f5ffff6078995bc8d2b334a62afe14de5",
  "model": "llama-3.1-8b",
  "prompt_sha256": "188b7c68248e3ea7e66b4ae359c4c0f1af898a4c388efb9d517d390537913a8d",
  "output": "Verifiable inference lets you audit what a remote node computed without trusting it. ",
  "output_sha256": "a88133a6f88e6558e00a8c82bbf4f6632e66ad43f332f7e4e8d7a02ee6815a32",
  "signature": "ed25519_sig:0cda89675d97deb2f04c4ceceda57d3d1332e9a8039a4f2941a83005ae89626058afe16a61be8e2b5a2956156088824b3c0a8b8ebf26d935ff9347fef9342a02"
};
